### PR TITLE
Remove jQuery

### PR DESCRIPTION
**Pull request by raffij**
Remove jQuery from SirTrevorJS.

Based on browser usage we can now remove jQuery. We will now rely on native functionality polyfilled where possible and utility functions provided by SirTrevorJS where jQuery functions were used.

@ninjabiscuit take a look and see what changes should be made.

### CODE REVIEW

**Comment by dwb** [comment]
Cor! :+1: :+1: :bomb: :sparkles:

**Comment by lukaszsagol** [comment]
Huge <3 for the migration documentation :clap:

**Comment by raffij** [comment]
@lukaszsagol Needs more work, but wanted to give ninja something to work with and rebase from soon. A thought is some sort of compatibility layer over the top too, so that people that are used to jQuery can use SirTrevor as they have before.

**Comment by andrewsprinz** [comment]
:clap: :clap: :+1:

**Comment by dwb** [comment]
Compatibility layer? That sounds painful... Surely the time is right to just drop jQuery altogether?

**Pull request merged**
