### PR TITLE
Implement block nesting functionality: Columns block

### PR DESCRIPTION
**Pull request by e1himself**
Hi!

I've prepared columns/nested blocks functionality for pull request:
* cleaned code and cherry-picked only necessary changes
* created needed svg icons instead of png sprite for columns icons
* used icomoon to handle icons font

Here's the demo: http://demo.e1stuff.com/sir-trevor/

### CODE REVIEW

**Comment by SebAshton** [comment]
Any update on this feature?

**Comment by e1himself** [comment]
Hi everyone!

Here's the new pull-request with core patch only. That will allow linking columns block as a plugin.
https://github.com/madebymany/sir-trevor-js/pull/297

**Comment by dwb** [comment]
Closing this because #297 was closed. Sorry people.

**Comment by Starefossen** [comment]
👎🏼

**Pull request closed without merging**
