### PR TITLE
added radio and checkbox feature

### PR DESCRIPTION
**Pull request by datazuul**
Fixes Issue: "Radio buttons are ignored when data is serialized #352"
and also checkboxes.

So advanced Block forms with radio-groups and checkboxes are possible (e.g. an image-upload with additional radios for alignment "left", "right")

### CODE REVIEW

**Comment by ilyaporopudas** [comment]
Looks good to me!

@raffij?

**Comment by raffij** [comment]
This is something I've been thinking about as part of a bigger project to
modify the way blocks are created.

I think data-name is a good approach as it reflects the native name
attribute.

It would be good to get a couple of tests in there to show both data is
being saved and loaded.

Once that's done we can merge it.

**Comment by datazuul** [comment]
For tests:
we are using the feature with a custom image upload block with these
widgets: image upload button, field for known unique id of an image,
Two radio groups: one for alignment left/right, the other for desired
scaling of the image to be embedded in page (25%, 33%, 50% or 100% width),
and finally the thumbnail image of the uploaded image

here is our working image block code (from the generated sir-trevor.js):

    /*
     Simple Image Block, requires:
     - jquery.fileupload.js
     - jquery.ui.widget.js
     - fileUploadModal.js
     */

    "use strict";

    var $ = __webpack_require__(56);
    var Block = __webpack_require__(195);

    module.exports = Block.extend({
      type: "image",
      title: function () {
        return i18n.t('blocks:image:title');
      },
      icon_name: 'image',
      editorHTML: function () {
        var blockId = this.blockID;
        return '<div class="imageBlock">' +
                '<div class="imageUpload">' +
                '  <a class="btn btn-primary btn-xs open-upload-modal">Bild
auswählen</a> oder bekannte ID eingeben<br/>' +
                '  <input type="text" class="js-image-id" data-name="id"/>'
+
                '</div>' +
                '<div class="imageFormatting">' +
                '  <b>Ausrichtung:</b> <input type="radio" name="' +
blockId + '-position" data-name="position" value="left">links <input
type="radio" name="' + blockId + '-position" data-name="position"
value="right">rechts<br/>' +
                '  <b>Breite:</b> <input type="radio" name="' + blockId +
'-width" data-name="width" value="25%">25% <input type="radio" name="' +
blockId + '-width" data-name="width" value="33%">33% <input type="radio"
name="' + blockId + '-width" data-name="width" value="50%">50% <input
type="radio" name="' + blockId + '-width" data-name="width"
value="100%">100%' +
                '</div>' +
                '</div>';
      },
      loadData: function (data) {
        // Create our image tag
        this.$('.js-image-id').val(data.id);
        this.$('.js-image-id').after($('', {src: data.thumbnailUrl,
class: "thumbnail"}));

        // set radio button value for position
        this.$('input[name="' + this.blockID + '-position"][value="' +
data.position + '"]').prop("checked", true);
        // set radio button value for width
        this.$('input[name="' + this.blockID + '-width"][value="' +
data.width + '"]').prop("checked", true);
      },
      onBlockRender: function () {
        this.$('.open-upload-modal').bind('click', function (ev) {
          configureUploadModal(function (data) {
            var $input = this.$('.js-image-id');
            $input.val(data.name);
            this.$inner.find('img').remove();
            $input.after('');
          }.bind(this));
          $('#uploadModal').modal('show');
        }.bind(this));
      }
    });


2015-11-28 19:08 GMT+01:00 Raffi Jacobs <notifications@github.com>:

> This is something I've been thinking about as part of a bigger project to
> modify the way blocks are created.
>
> I think data-name is a good approach as it reflects the native name
> attribute.
>
> It would be good to get a couple of tests in there to show both data is
> being saved and loaded.
>
> Once that's done we can merge it.
>

**Comment by morpheus-87** [comment]
I am working with @datazuul on this code. Is there a recommended way to write test-blocks?
I will update the code for the sir trevor version 0.5.0. Is this ok?
We want to contribute this in the next days.

**Comment by raffij** [comment]
@morpheus-87 let's have a think.

These changes are to 0.5, which is very old now. Looking to release 0.6 in the very near future.

The changes to the interface in 0.6 are quite big, so probably worth staying on your branch for now.

To apply your changes to master you'll want to rewrite them in the correct location for the latest code base.

**Comment by morpheus-87** [comment]
Can you tell us, when version 0.6 is going to be released? In our project we really need this feature, but the deadline is in the end of august.

**Comment by raffij** [comment]
@morpheus-87 going to reference your pr and create a new one for the master branch. Following on from your other issue created today can work out if this one wants to also be rebased to a 0.5.0 branch for not.

**Comment by raffij** [comment]
@morpheus-87 i've added a pr which will add this functionality slightly modified to 0.6.

**Pull request closed without merging**
