### PR TITLE
Fixed drag drop behaviour for elements that are not blocks and should not be dropped between blocks.

### PR DESCRIPTION
**Pull request by gmoreira**
To replicate this issue using the provided sample page, create a text or heading block and type something into it. Then, select the text you just typed and click drag it around the page. Dragging it around you will trigger the dropzones between blocks. Dropping the text into a dropzone will leave the dropzone in the wrong state and it continues to show the "Drop block here" text.

### CODE REVIEW

**Comment by ninjabiscuit** [comment]
this looks good but seems to cause broken tests

**Comment by gmoreira** [comment]
The build was broken on Master which is why it was failing. Updated my branch from Master to verify this.

**Comment by ninjabiscuit** [comment]
Hi, looks like we had a problem with our test setup where tests were
running for core team members but not anyone else.

This "should" be fixed now. Can you pull master into your branch and and
push to your PR again plz?

**Comment by gmoreira** [comment]
Isn't that what I did earlier?

**Comment by zgryw** [comment]
Great stuff!

**Pull request merged**
