### PR TITLE
Delete an uploaded file

### PR DESCRIPTION
**Pull request by jackbot**
When a block is mixed in with `uploadable`, the file is uploaded as soon as it's dropped on the block. If the block is then deleted the image remains on the server. This commit just makes an ajax request with the block UID so the file can be deleted by whatever backend is in place.

### CODE REVIEW

**Comment by zgryw** [comment]
@jackbot I think that the whole idea is great, however I have some comments on how to make it a bit better:

- it'd be nice if this behaviour was configurable, so if someone doesn't need it, they can disable it
- i think that Uploadable mixin is a better place for this code, you could make use of `SirTrevor.EventBus` and `block:remove` event
- test wise I'd prefer to have a separate function responsible for sending the request and spying on that function getting called, because spying on `ajax` being called doesn't really test the right thing

I'll be really happy to merge your PR afterwards, I think it's an awesome thing and would be really useful to have.

**Comment by SgtOddball** [comment]
Has there been any further work on this or is it currently waiting on responses/tweaks? 

If it's currently stalled I might be interested in having a looksee when I've got some time.

**Comment by zgryw** [comment]
I don't think anyone is working on it right now. It'd be great if you could take a look and incorporate proposed changes!

**Comment by kapouer** [comment]
Hi,
resources (files, data, links) and blocks should be many-to-many, to one-to-one.
Adding or removing a resource from a block could generate events that'd be useful to maintain a list of (un)used resources in an editor environment. When a resource is no longer used it could be either suppressed from server or anything else - at the discretion of the user code, not forced by sir-trevor.

**Pull request closed without merging**
