### PR TITLE
Patch core to allow linking plugins with nesting blocks functionality

### PR DESCRIPTION
**Pull request by e1himself**
Related to [Implement block nesting functionality: Columns block](https://github.com/madebymany/sir-trevor-js/pull/177) Pull Request.

As stated in [my comment](https://github.com/madebymany/sir-trevor-js/pull/177#issuecomment-56807244) to the pull request above,
I've moved the minimum changes to Sir Trevor Core to allow have plugin blocks, that can contain another blocks in it. The original *Columns Block* was moved to [separate repository](https://github.com/e1himself/sir-trevor-columns-block).

Summary of changes:

* Pass SirTrevor Editor instance to Block Manager
* Pass SirTrevor Editor instance to Blocks on creation
* Pass render_at argument to Editor._renderInPosition function (to define container where block should be rendered)
* Iterate over blocks carefully. In most cases instead of this.find('.st-block') we should do this.children('.st-block') to select only top-level blocks
* Add stopPropagation() calls on some events (to not bubble up to parent block)
* Restrict styling to only one-level deep (not to affect possible nested blocks)

Why should we pass editor instance to blocks? Advanced blocks with nesting functionality need to call:

* `SirTrevor.Editor.removeBlock() `
* `SirTrevor.Editor.createBlock() `
* `SirTrevor.Editor.findBlockById() `

Though the first call can be replaced with trigerring events, the other two are pushing us to pass editor instance.

Also I'm pretty sure that spec tests should be improved.

### CODE REVIEW

**Comment by gmoreira** [comment]
+1 for these changes.

Any thoughts or feedback on this @ninjabiscuit @cjbell ?

**Comment by bborn** [comment]
+1 for this. Any update on whether/how this could get into core?

**Comment by timonweb** [comment]
+1, waiting for this merge!

**Comment by ninjabiscuit** [comment]
Hi everyone. Sorry it's taken me so long to reply to this. We've been having a lot of internal discussions about how to move forward with Sir Trevor. Looking at how people use/implement ST and the work we need to do to get us to 1.0. 

As a part of that we spent some time debating this PR and have come to the conclusion that, even without most of the nested block functionality. We're still not prepared to merge it into core. 

I'll explain why, but firstly let me say that we really appreciate your work with this, your continued contributions, ideas and desire to make ST better. 

The fact is, for reasons described in the previous PR, we're not prepared to make any reference to nested blocks in core as it's not a use case we really agree with.

The updates that you've made to the block manager make [specific reference to nested blocks](https://github.com/madebymany/sir-trevor-js/pull/297/files#diff-02693d392b25d09c299e0d28c3d8151eR72) and that's something we're not prepared to compromise on.

What we did like about the pull request was the update to remove editorID in favour of the actual editor instance. As you commented in the PR, editorID is pretty useless.

I was also pleased to see the addition of `stopPropagation` on the block reorderer as that also makes total sense.

I really think that those additions would be valuable to the ST project but, I'm afraid, we won't budge on referencing nested blocks in core. 

I hope that makes sense and that it doesn't deter you from contributing to this project.

**Comment by e1himself** [comment]
Hi everyone,

If anyone needs columns layout functionality, you can use [sir-trevor-columns-block](https://github.com/e1himself/sir-trevor-columns-block) plugin with [mr-trevor-js](https://github.com/e1himself/mr-trevor-js-bower) - a fork of Sir Trevor with patched core. Installable via bower.

**Comment by firedev** [comment]
Wow, this is amazing. Think it would be possible to drag and drop blocks between columns?

**Comment by e1himself** [comment]
@firedev 

Yep. Drag and Drop it is supported by sir-trevor-columns-block plugin.

**Comment by Starefossen** [comment]
@ninjabiscuit :-1:

**Pull request closed without merging**
