### PR TITLE
Extending the available block types with an ordered list

### PR DESCRIPTION
**Pull request by morpheus-87**
This pull request extends the block types, that are available by default, with an ordered list.

### CODE REVIEW

**Comment by raffij** [comment]
@morpheus-87 thanks for this pull request.

This is something I've been thinking about and one of the reasons why I fixed up the block controls in 0.6.

My preference would be to have 1 list block and give the user the option to select between the type. So the first step for us would be to generalise the list block and programatically select the list type rather than hardcode the template. Then if you really did want a secondary list block then that could be preselected in your own list block in your repo.

**Comment by SgtOddball** [comment]
@raffij That makes more sense having the one block. 

As a related question though, would list nesting be allowed? (ie. 1 > a > i,ii,iii etc.)

**Comment by raffij** [comment]
@SgtOddball indented lists is something that has been asked about before. Before doing this I need to improve the keyboard navigation for lists, as that has some bugs.

**Comment by SgtOddball** [comment]
@raffij Thats fine, the thought occurred to me when I saw this. That was all.

**Comment by raffij** [comment]
Initial thoughts on unordered / ordered lists and indentation https://github.com/madebymany/sir-trevor-js/compare/indented-lists?expand=1

**Pull request closed without merging**
