### PR TITLE
add cn-TW locale

### PR DESCRIPTION
**Pull request by simoniong**
This is a PR for adding a Chinese Traditional locale for Sir-Trevor Js.

Please let me know if you have any issue regards on naming, or translation. 💃

### CODE REVIEW

**Comment by raffij** [comment]
@matthewrudy is this good?

**Comment by matthewrudy** [comment]
@raffij looks fine.
But normally the locale is `zh-TW`
(Or if you're following the iso standard itd be `zh-Hant`)

For comparison take a look at Rails' translations
https://github.com/svenfuchs/rails-i18n/blob/master/rails/locale/zh-TW.yml

They use slightly different terms for `blank`

**Comment by matthewrudy** [comment]
Ah, I get it.
This is a conversion of `cn.js` to use traditional characters.

So my original point still stands `cn` is not a locale.

Should really be `zh` for Chinese.

So `zh-cn` and `zh-tw` is the most common choice.

**Comment by raffij** [comment]
@simoniong if you change the locale name then I can merge for you.

**Comment by raffij** [comment]
Thanks @matthewrudy for checking the language

**Comment by simoniong** [comment]
Hey, @matthewrudy, I just rename `cn.js` to `zh-cn.js` for Chinese Simplified , and for Chinese Tranditional local, i have renamed it into `zh-tw.js`. Please let me know if i am doing it right. 😄

**Comment by raffij** [comment]
Thanks to you both

**Pull request merged**
