### PR TITLE
Make included blocks work well with Markdown and Scribe

### PR DESCRIPTION
**Pull request by zgryw**
Code responsible for serialising to HTML/Markdown is in `block.js` (depending on the setting `convertToMarkdown`).

Unfortunately, code responsible for loading data is in specific blocks, therefore I had to override `getData` function in every block, and depend behaviour based on `convertFromMarkdown` setting.

Now all base blocks should support content created with previous versions but also (possibly) saving back to markdown, even though we'll remove that feature sooner or later.

Also added dist files to root of the project, to make using/testing with bower easier. 

Related to #313, #314 - both Heading and List block should now behave just like in previous versions (they need some functional improvements, but that's for separate PRs).

### CODE REVIEW

**Comment by gmoreira** [comment]
When I reviewed the #301 I wondered why we hadn't used that flag `convertToMarkdown`. 
Good to see this change bringing all the blocks into alignment! Nice work!

**Comment by zgryw** [comment]
Finally we decided not to support Markdown as a data format for v0.5 of SirTrevor. Supporting both HTML and Markdown would be difficult (and would mean that for Markdown support we turn off Scribe completely) and stop us from moving forward.

Of course SirTrevor will still work fine with content created in previous versions, converting them to HTML and saving them in that format.

Ping @ninjabiscuit @gmoreira

**Comment by gmoreira** [comment]
Sounds fine to me!

**Comment by ninjabiscuit** [comment]
:shipit: :rocket:

**Pull request merged**
