### PR TITLE
Limit image upload to image files by MIME type

### PR DESCRIPTION
**Pull request by SgtOddball**
Added ```accept``` restriction to limit files to only images.

Small tweak I know but it was bugging me about having all the files in one my folders showing.

### CODE REVIEW

**Comment by dwb** [comment]
Hi, please amend your commit to have the text in the first line; "Update image.js" doesn't say anything useful. Likewise, more descriptive PR titles would be appreciated. Cheers.

**Comment by SgtOddball** [comment]
Sorry my bad, I'll expand it further.

**Comment by dwb** [comment]
I was referring to the title of your commit; see [this](https://help.github.com/articles/about-git-rebase/) for how to amend existing commit messages and then you can `git push -f` to replace the head on the remote. Do heed the warning though: this shouldn't be done with commits other people have pulled or committed on top of. This is also why it's a good idea to make a new branch in your repository for PRs. I've also made the PR title more concise.

**Comment by SgtOddball** [comment]
I'm still getting to grips with git and so far I've mainly been doing it all through the github website. 

As to the repository, I thought I had branched it? I'll have to spend more time going over it to see where I was going wrong.

**Comment by dwb** [comment]
You’ve “forked" the repository, that is, cloned it and added it to your GitHub account. Creating a new branch would be within your forked repository. I suggest the Pro Git book here for learning more about Git: http://git-scm.com/book/en/v2 <http://git-scm.com/book/en/v2>

Note that if you do make commits through the website the “Updated $file” text is just a default you can replace with your own. Typically you write a 72-character summary in the first line, and if there’s any more information you can give, an expansion in the lines below. It’s much better to get to grips with Git properly though, as then you can bring changes in many files into one commit: commits are meant to be atomic chunks of changes with a meaningful, human-readable, high-level summary. Also just committing changes on the GitHub website make it harder to run the tests to check what you’ve changed hasn’t broken anything.

**Pull request closed without merging**
